#!/bin/sh
#
# libslack - http://libslack.org/
#
# Copyright (C) 1999-2001 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# Modify the macros.mk make include files to compile on Solaris with cc
#
# 20010215 raf <raf@raf.org>

perl -pi \
	-e 's/^# (\S+ \+= xnet)$/$1/;' \
	-e 's/^# (\S+ \+= posix4)$/$1/;' \
	-e 's/^# (\S+ \+= m)$/$1/;' \
	-e 's/^# (\S+ \+= -DSVR4)$/$1/;' \
	-e 's/^# (GETOPT := getopt)$/$1/;' \
	-e 's/^# (\S+ \+= -DNEEDS_GETOPT=1)$/$1/;' \
	-e 's/^(SNPRINTF := snprintf)$/# $1/;' \
	-e 's/^(\S+ \+= -DNEEDS_SNPRINTF=1)$/# $1/;' \
	-e 's/^# (VSSCANF := vsscanf)$/$1/;' \
	-e 's/^# (\S+ \+= -DNEEDS_VSSCANF=1)$/$1/;' \
	-e 's/^# (\S+ \+= -DMLOCK_NEEDS_PAGE_BOUNDARY=1)$/$1/;' \
	-e 's/^# (\S+ \+= -DROOT_PID_DIR)=.*$/$1=\\"\/etc\\"/;' \
	-e 's/^(\S+ \+= -DNEEDS_STRCASECMP=1)$/# $1/;' \
	-e 's/^(\S+ \+= -DNEEDS_STRNCASECMP=1)$/# $1/;' \
	-e 's/^# (\S+ \+= -DNEEDS_STRLCPY=1)$/$1/;' \
	-e 's/^# (\S+ \+= -DNEEDS_STRLCAT=1)$/$1/;' \
	-e 's/^# (\S+ \+= -DWANT_LONG_LONG=1)$/$1/;' \
	-e 's/^(\S+ \+= -Wno-long-long)$/# $1/;' \
	-e 's/^# (\S+ \+= -DNEEDS_PTHREAD_RWLOCK=1)$/$1/;' \
	-e 's/^# (\S+ \+= -DNEEDS_PTHREAD_BARRIER=1)$/$1/;' \
	`find . -name macros.mk`

perl -pi \
	-e 's/^(CC := gcc)$/# $1/;' \
	-e 's/^(CCFLAGS \+= -O2)$/# $1/;' \
	-e 's/^(CCFLAGS \+= -Wall -pedantic)$/# $1/;' \
	-e 's/^# (CC := cc)$/$1/;' \
	-e 's/^# (CCFLAGS \+= -O)$/$1/;' \
	`find . -name Makefile`

