#!/bin/sh
#
# libslack - http://libslack.org/
#
# Copyright (C) 1999-2010 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# Revert to system implementation of rwlocks
#
# 20100612 raf <raf@raf.org>

perl -pi \
	-e 's/test_pthread_rwlock/pthread_rwlock/g;' \
	-e 's/\bTEST_PTHREAD_RWLOCK/PTHREAD_RWLOCK/g;' \
	${@:-`find . -name '*.[ch]'`}

perl -pi \
	-e 's/^# (\S+ \+= -DHAVE_PTHREAD_RWLOCK=1)$/$1/;' \
	`find . -name macros.mk`

perl -pi \
	-e 's/^\/\* #undef (HAVE_PTHREAD_RWLOCK) \*\/$/#define $1 1/;' \
	`find . -name config.h`

