#!/bin/sh
#
# libslack - http://libslack.org/
#
# Copyright (C) 1999-2001 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# 20020916 raf <raf@raf.org>

die() { echo "$0: $@" >&2; exit 1; }

case "`uname -a`" in
	Linux*)
		conf/linux
		;;

	FreeBSD*)
		conf/freebsd
		;;

	OpenBSD*)
		conf/openbsd
		;;

	SunOS*)
		cc=""
		solaris="solaris8"
		[ "x`uname -r`" = "x5.6" ] && solaris="solaris6"
		[ "x`which gcc 2>/dev/null`" != "x" ] && cc="gcc"
		[ "x`which cc 2>/dev/null`"  != "x" ] && cc="cc"
		[ "$cc" = "" ] && die "Failed to find a compiler"
		conf/$solaris-$cc
		;;

	*)
		die "Unknown platform: please configure manually"
		;;
esac

exit 0

# vi:set ts=4 sw=4
