#
# libslack - http://libslack.org/
#
# Copyright (C) 1999-2001 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#
# 20010215 raf <raf@raf.org>

=head1 NAME

I<libslack-config> - administrative tool for libslack

=head1 SYNOPSIS

 libslack-config [options]
 options:

   -h, --help     - Print this help and exit
   -v, --version  - Print the version of the currently installed libslack
   -L, --latest   - Print the latest version of libslack (uses wget and perl)
   -D, --download - Download the latest version of libslack (uses wget)
   -p, --prefix   - Print prefix of libslack installation
   -c, --cflags   - Print CFLAGS needed to compile clients of libslack
   -l, --libs     - Print LDFLAGS needed to link against libslack

 Command line example:
   gcc -o app app.c `libslack-config --cflags --libs`

 Makefile example:
   APP_CFLAGS  += $(shell libslack-config --cflags)
   APP_LDFLAGS += $(shell libslack-config --libs)

=head1 DESCRIPTION

I<libslack-config> is an administrative tool for I<libslack(3)>. It can
print the compiler and linker flags that are needed to compile and link
programs that use I<libslack(3)>. It can also print the version of the
currently installed I<libslack(3)> or print the latest version available at
L<http://www.libslack.org/|http://www.libslack.org/>. It can also download
the latest version.

=head1 OPTIONS

=over 4

=item C<-h>, C<--help>

Print a help message and exit.

=item C<-v>, C<--version>

Print the version of the currently installed I<libslack>.

=item C<-L>, C<--latest>

Print the latest version of I<libslack> available at
L<http://libslack.org/|http://libslack.org/>.

=item C<-D>, C<--download>

Download the latest version of I<libslack> from
L<http://libslack.org/|http://libslack.org/>.

=item C<-p>, C<--prefix>

Print the prefix directory under which I<libslack> was installed.

=item C<-c>, C<--cflags>

Print the compiler flags needed to compile code that uses I<libslack>.

=item C<-l>, C<--libs>

Print the linker flags needed to link code against I<libslack>.

=back

=head1 SEE ALSO

L<http://libslack.org/|http://libslack.org/>,
L<libslack(3)|libslack(3)>,
L<err(3)|err(3)>,
L<fio(3)|fio(3)>,
L<getopt(3)|getopt(3)>,
L<hsort(3)|hsort(3)>,
L<lim(3)|lim(3)>,
L<list(3)|list(3)>,
L<map(3)|map(3)>,
L<mem(3)|mem(3)>,
L<msg(3)|msg(3)>,
L<net(3)|net(3)>,
L<prog(3)|prog(3)>,
L<prop(3)|prop(3)>,
L<sig(3)|sig(3)>,
L<snprintf(3)|snprintf(3)>,
L<str(3)|str(3)>,
L<thread(3)|thread(3)>,
L<vsscanf(3)|vsscanf(3)>

=head1 AUTHOR

20010215 raf <raf@raf.org>

