#!/bin/sh

# Demonstrate daemon(1) with client1
#
# client1 prints 0 to 4 each on a line, sleeping 1 second before each line
# The daemon.conf file causes client1 to be run with debug=9, with output
# redirected to syslog destination daemon.err, and respawning. Terminate
# the demonstration be sending daemon a TERM signal.
#
# Note: Respawning won't occur unless libslack was compiled with
# RESPAWN_THRESHOLD less than 5 or client1 modified to run for more
# than 600 seconds.

../daemon -C "`pwd`/daemon.conf" -n client1 "`pwd`/client1"
